name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main, stag]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Skip deploy if commit message contains [skip deploy]
        run: |
          if git log -1 --pretty=%B | grep -q "\[skip deploy\]"; then
            echo "🛑 Skipping deploy due to commit message flag."
            exit 0
          fi

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Clone GitHub Pages repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Sohaib-Sana/Sohaib-Sana.github.io.git gh-pages
          cd gh-pages
          git config user.name "Sohaib Sana [Workflow bot]"
          git config user.email "dev.sohaibsana@gmail.com"

      - name: Deploy based on branch
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"

          if [ "$BRANCH_NAME" = "main" ]; then
            TARGET_DIR="."
          else
            TARGET_DIR="$BRANCH_NAME"
          fi

          rm -rf gh-pages/${TARGET_DIR}
          mkdir -p gh-pages/${TARGET_DIR}
          cp -r build/web/* gh-pages/${TARGET_DIR}/

          cd gh-pages
          touch ${TARGET_DIR}/.nojekyll
          git add ${TARGET_DIR}
          git commit -m "🚀 Deploy ${BRANCH_NAME} branch from portfolio repo"
          git push origin main

      - name: Send Telegram notification
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Successfully deployed '${BRANCH_NAME}' branch to Sohaib-Sana.github.io/${BRANCH_NAME}"
