name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Skip deploy if commit message contains [skip deploy]
        run: |
          if git log -1 --pretty=%B | grep -q "\[skip deploy\]"; then
            echo "🛑 Skipping deploy due to commit message flag."
            exit 0
          fi

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Deploy to Sohaib-Sana.github.io
        run: |
          git config --global user.name "Sohaib Sana [Workflow bot]"
          git config --global user.email "dev.sohaibsana@gmail.com"

          cd build/web

          git init
          git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Sohaib-Sana/Sohaib-Sana.github.io.git
          git checkout -b main

          touch .nojekyll
          git add .
          git commit -m "🚀 Auto-deploy from portfolio repository"
          git push --force origin main
